curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh
postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
postman collection run 52855131-3a26baac-39ca-4bfb-a469-82aa8fd1b654 --report-events
